stages:
  - test
  - build

test:
  stage: test
  image: gradle:7.4.2-jdk17
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle test

gradle-build:
  image: gradle:7.4.2-jdk17
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: gradle-cache
    paths:
      - .gradle/caches
