# Adding workflow rules to avoid other branches to use the pipeline
# since we only want to use the master branch
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - clean
  - build
  - test
  - deploy

clean:
  image: gradle:7.4.2-jdk17
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - sh $CI_PROJECT_DIR/gradlew clean

gradle-build:
  image: gradle:7.4.2-jdk17
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: gradle-cache
    paths:
      - .gradle/caches

test:
  stage: test
  image: gradle:7.4.2-jdk17
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle test

static-code-analysis:
  image: gradle:7.4.2-jdk17
  stage: test
  script:
    - echo "Running Static Code Analysis..."
    - echo "Evaluate Violations..."
    - sh $CI_PROJECT_DIR/gradlew evaluateViolations

heroku-deploy:
  image: docker:stable
  stage: deploy
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login --username=$HEROKU_USER --password=$HEROKU_API_KEY registry.heroku.com
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build --build-arg JAR_FILE=`ls build/libs/*.jar | head -1` --tag registry.heroku.com/$HEROKU_APP_NAME/web .
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web
    - ./release-docker-in-heroku.sh $HEROKU_APP_NAME $HEROKU_API_KEY