# Adding workflow rules to avoid other branches to use the pipeline
# since we only want to use the master branch
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - clean
  - build
  - test
  - visualize

clean:
  image: gradle:7.4.2-jdk17
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - sh $CI_PROJECT_DIR/gradlew clean

gradle-build:
  image: gradle:7.4.2-jdk17
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: gradle-cache
    paths:
      - .gradle/caches

test:
  stage: test
  image: gradle:7.4.2-jdk17
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle test

test reports:
  stage: test
  script:
    - bundle install
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml

static-code-analysis:
  image: gradle:7.4.2-jdk17
  stage: test
  script:
    - echo "Running Static Code Analysis..."
    - echo "Evaluate Violations..."
    - sh $CI_PROJECT_DIR/gradlew evaluateViolations
