version: 2
jobs:
  build:
    docker:
      - image: gradle:7.4.2-jdk17


    working_directory: ~/repo

    steps:
      -checkout

      - restore-cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-

      - run: yarn install

      -save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json"}}

      -run: yarn test