name: Github Workflow
on:
  push:
    branches:
      - main
jobs:
  gradle-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
      - run: sh ./gradlew clean

  gradle-build:
    runs-on: ubuntu-latest
    needs: gradle-clean
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build

  gradle-test:
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew test

  deploy-on-dev:
    runs-on: ubuntu-latest
    needs: gradle-test
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_USER}}
          dontuseforce: true
          dontautocreate: true

  validate-deploy:
    runs-on: ubuntu-latest
    needs: deploy-on-dev
    steps:
      - uses: actions/checkout@v2
      - uses: jirutka/setup-alpine@v1
      - run: pip install urllib3
      - run: python src/test/acceptance/acc01.py ${{secrets.HEROKU_APP_NAME}}
      - run: python src/test/acceptance/acc02.py ${{secrets.HEROKU_APP_NAME}}
      - run: python src/test/acceptance/acc03.py ${{secrets.HEROKU_APP_NAME}}
      - run: python src/test/acceptance/acc04.py ${{secrets.HEROKU_APP_NAME}}
      - run: python src/test/acceptance/acc05.py ${{secrets.HEROKU_APP_NAME}}
      - run: python src/test/acceptance/acc06.py ${{secrets.HEROKU_APP_NAME}}

  deploy-on-prod:
    runs-on: ubuntu-latest
    needs: [ deploy-on-dev,validate-deploy ]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_PROD}}
          heroku_email: ${{secrets.HEROKU_USER}}
          dontuseforce: true
          dontautocreate: true