name: Github Workflow
on:
  push:
    branches:
      - main
jobs:
    validate-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - run: pip install urllib3
        - run: python src/test/acceptance/acc01.py $HEROKU_APP_NAME_PROD

