name: Github Workflow

on:
  push:
    branches:
      - master




jobs:
  clean:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 11

        - name: Make gradlew executable
          run: chmod +x ./gradlew

        - name: Echo
          uses: echo "Cleaning leftovers from previous builds"

        - name: Execute Gradle clean
          run: ./gradlew clean

  gradle-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build