name: Github Workflow
on:
  push:
    branches:
      - main
jobs:
    deploy:
      runs-on: ubuntu-latest
      timeout-minutes: 20
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - uses: akhileshns/heroku-deploy@v3.2.6
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME_PROD}}
            heroku_email: ${{secrets.HEROKU_USER}}
            dontuseforce: true
            dontautocreate: true

    validate-deploy:
      runs-on: python:alpine
      needs: deploy
      steps:
        - run: pip install urllib3
        - run: python src/test/acceptance/acc01.py $HEROKU_APP_NAME_PROD
